global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'docker-swarm'
    static_configs:
      - targets:
          - '172.31.11.115:30000' # cadvisor
          - '172.31.11.116:30000' # cadvisor
          - '172.31.11.117:30000' # cadvisor
          - '172.31.11.118:30000' # cadvisor
          - '172.31.11.119:30000' # cadvisor
  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '192.168.66.21:30001' # node_exporter

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
      - targets:
          - 'alertmanager:9093'

rule_files:
  - "/etc/prometheus/rules/cpu.yaml"
